body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Have a look at current discussions to see if anyone else has mentioned your
        > project.

  - type: textarea
    attributes:
      label: Project information
      description: |
        Share some basic information about this project
      value: |
        - **Project name**:
        - **Project website**:
        - **Code repository**:
        - **License**:
    validations:
      required: true

  - type: checkboxes
    id: owner-confirmation
    attributes:
      label: Do you have authority to represent this project?
      options:
        - label: I own or maintain this project
          required: true

  - type: textarea
    attributes:
      label: Describe your project
      description: |
        Be descriptive but concise.
        - What language is it written in?
        - What does it do?
        - How is it affiliated with or related to open source?
      placeholder: "<Project Name> allows folks to <better do something>."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation for joining Commonhaus
      description: |
        - What are you hoping to get out of joining Commonhaus?
        - Why Commonhaus as opposed to other organizations?
        - Any questions or concerns about joining Commonhaus?
      placeholder: "I think <Project Name> would be a good candidate for Commonhaus because <reasons>."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Things to review before submitting
      description: |
        Please use this discussion to ask any clarifying questions you may have
        before completing these tasks.
      value: |
        - [ ] **Review the bylaws**, especially sections about [projects](https://www.commonhaus.org/bylaws/cf-membership.html#projects),
            [decision making](https://www.commonhaus.org/bylaws/decision-making.html),
            and [voting for significant decisions](https://www.commonhaus.org/bylaws/cf-council.html#voting).
        - [ ] **Review the [Fiscal Sponsorship Terms and Conditions](https://www.commonhaus.org/policies/fiscal-sponsorship/)**.
            These outline the legal and financial framework for how we support projects.
        - [ ] If all is well, and you agree to move forward, then **create a PR** with the following:

            1. An updated [CONTACTS.yaml](https://github.com/commonhaus/foundation/blob/main/CONTACTS.yaml) that names your project representative in the EGC section
            2. An updated [PROJECTS.yaml](https://github.com/commonhaus/foundation/blob/main/PROJECTS.yaml) that provides details / describes your project
            3. An updated [TRADEMARKS.md](https://github.com/commonhaus/foundation/blob/main/TRADEMARKS.md) that adds your project name and project logo (if you have one).
                Please include the footnote reference, as we are using your project name and logo with your permission until a formal agreement is in place and assets are transferred.

            The commit should be "Signed-off-by" your GH login (`git commit -s -m "<project> joining request, yyyy-mm-dd"`)
    validations:
      required: true
