name: Push discussions and PR activity to commonhaus.github.io

on:
  discussion:
  pull_request_target:
    types: [opened, edited, reopened, closed]
    paths:
      - '*.md'
      - '*.yaml'
      - 'bylaws/**'
      - 'policies/**'
  push:
    branches:
      - main
    paths:
      - '*.md'
      - '*.yaml'
      - 'bylaws/**'
      - 'policies/**'
  workflow_dispatch:

permissions: {}

jobs:
  update-website:
    runs-on: ubuntu-latest
    if: github.repository == 'commonhaus/foundation'
    permissions:
      actions: read
    steps:
    - name: Bump website
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_PUBLISH_PAT }}
      run: |
        gh workflow run -R commonhaus/commonhaus.github.io push-content.yml
